export const cities = [
  { label: "New York", value: "JFK" },
  { label: "Los Angeles", value: "LAX" },
  { label: "Chicago", value: "ORD" },
  { label: "San Francisco", value: "SFO" },
  { label: "Seattle", value: "SEA" },
  { label: "Miami", value: "MIA" },
  { label: "Boston", value: "BOS" },
  { label: "Las Vegas", value: "LAS" },
  { label: "Washington, D.C.", value: "DCA" },
  { label: "Denver", value: "DEN" },
  { label: "Atlanta", value: "ATL" },
  { label: "Dallas", value: "DFW" },
  { label: "Houston", value: "IAH" },
  { label: "Phoenix", value: "PHX" },
  { label: "Philadelphia", value: "PHL" },
  { label: "Minneapolis", value: "MSP" },
  { label: "Detroit", value: "DTW" },
  { label: "San Diego", value: "SAN" },
  { label: "Orlando", value: "MCO" },
  { label: "Charlotte", value: "CLT" },
  { label: "Tampa", value: "TPA" },
  { label: "Baltimore", value: "BWI" },
  { label: "Salt Lake City", value: "SLC" },
  { label: "New Orleans", value: "MSY" },
  { label: "Portland", value: "PDX" },
  { label: "Cincinnati", value: "CVG" },
  { label: "San Jose", value: "SJC" },
  { label: "Cleveland", value: "CLE" },
];
